### ISSUE TITLE
Text Colour when using Dark theme on HA

### ISSUE THREAD

**Issue by seangordon** [oatybiscuit/Node-RED-HA-Octopus-Agile-JSONata#3]
The Octopus Agile Rates table assumes that the HA light theme is configured
When the HA theme is set to dark - the text on the import graph is not readable as it is white text on a red / yellow / green background...

<img width="487" alt="Screenshot 2024-02-22 at 16 10 59" src="https://github.com/oatybiscuit/Node-RED-HA-Octopus-Agile-JSONata/assets/15179276/a06e87a8-f41d-49b2-928e-51008c96dbef">

**Comment by oatybiscuit** [comment]
I suggest that you change the colours hard-coded into the div section to something darker in the configuration, change the foreground to black, or remove this feature completely.

To make this (simple) display respond to _both_ light and dark would require uplifting the current theme settings and making a decision for a complementary background colour. This is not something that I know how to do. I personally only use light standard theme as I find this more readable.

**Comment by oatybiscuit** [comment]
Additional suggestions for colours added to the read.me. Uses a light yellow for text and medium tone colours to achieve a contrast ratio of close to 4.5 or better, to deal with both light and dark display themes.

If anyone knows how to read the current theme text / background colour, and has the code to generate RAG colour set from this that can be read, meets contrast disability requirements, and can manage various colour blindness conditions, please contribute.

The other solution, of course, is to ditch the colour idea altogether and add a new column with '!' for high prices, and '-' for low prices ( ' ' for the mid range). This is left as an exercise for the reader. Thank you.

**Comment by seangordon** [comment]
Looking at the HA docs, the challenge in this case is that the HA theme light or dark sets the label text to be black (light theme) or white (dark theme).
Since the text for the Import Tariff is being displayed on red/yellow/green background the colour of this text should always be set to black, since we know that in this column the text will always be displayed on a red/yellow/green background and so the text colour should not be driven by the HA theme selection - black text renders correctly in this column in either theme.
I think the simple solution is to explicitly set the text colour to black for that specific Import column, then it will work correctly regardless of the HA theme.
